namespace: joltcan

name: opconnect

version: 1.0.0

readme: README.md

authors:
  - Fredrik Lundhag <f@mekk.com>

description: Lookup 1Password connect items

license:
  - GPL-3.0-or-later

tags: ['onepassword', 'onepasswordconnect', 'opconnect', 'security', 'secret']

dependencies: {}

repository: https://github.com/joltcan/ansible-opconnect-collection

documentation: https://github.com/joltcan/ansible-opconnect-collection

homepage: https://github.com/joltcan/ansible-opconnect-collection

issues: https://github.com/joltcan/ansible-opconnect-collection/blob/main/

build_ignore: ['scripts', '.venv', 'tests', 'dist']
